name: up_menus
description: Api for the Univesity of Porto establisments menus
version: 1.0.0
repository: https://github.com/niaefeup/up_menus

environment:
  sdk: '>=3.0.0-edge.d5bd015cac5c620f46209c9db0b9ce2c4d9510d0 <4.0.0'

# Add regular dependencies here.
dependencies: 
  http: ^0.13.6
  json_annotation: ^4.8.1 

dev_dependencies:
  build_runner: ^2.4.3
  json_serializable: ^6.6.2
  lints: ^2.0.0
  test: ^1.21.0

scripts:
  build: dart run build_runner build